version: '3'
services:
  nytscrape:
    build: ./nytScrape
    volumes:
     - .:/code
  buildrestapi:
    build: ./buildrestapi
    ports:
      - "10000:10000"
  react-api:
    build: ./react-api
    ports:
      - "3000:3000"
